### ISSUE TITLE
Featured image is not showing with post

### ISSUE THREAD

**Issue by poonam279** [Codeinwp/zerif-lite#608] opened 2017-08-28 08:57 UTC
@rodica-andronache In the latest version (1.8.5.28) featured image is not showing with the blog post.
Before: http://prntscr.com/gdxa1s 
Now: http://prntscr.com/gdxa9c

**Comment by weellu** [comment] 2017-08-30 17:02
I think the problem is introduced even before 1.8.5.28. I rolled back to 1.8.5.25 and then the problem was fixed. So it might be that the problem has been introduced already in 1.8.5.26. However, just guessing here. I hope it will be fixed soon. I am suffering from the same problem.

**Comment by rodica-andronache** [comment] 2017-09-02 14:25
@poonam279 thanks :)

**Closed as completed by rodica-andronache** 2017-09-02 14:25 UTC
