### ISSUE TITLE
Team member image do not upload if "Upload Image" button is translated.

### ISSUE THREAD

**Issue by Vishakha-Patel** [Codeinwp/zerif-lite#632] opened 2017-12-28 10:11 UTC
@rodica-andronache 

When the Upload image button in Team widget is translated especially with a special character like apostrophe or something, the URL text field shows the button title instead of image URL. Like this - https://themeisle.com/index.php?gf-download=2017%2F12%2Fzerif-our-team-widget-siteorigin.png&form-id=1&field-id=19&hash=93397b416fbdd8457c9a3ec73455b299bd2a156fbd45b8bfd95c57078ac79049

Thus the image does not get displayed on the front end.

While I could not replicate it on my end but I have seen this problem couple times only when the button is translated. And translated into a language which has special characters.

https://secure.helpscout.net/conversation/489698698/150516/ - First message from client explains the problem.

If it is not a bug please close.

**Comment by gschutz84** [comment] 2018-01-03 11:42
I stumbled about the same issue, but I'm not sure it's the translation. The problem is the same as above mentioned, choosing an image works and the link is inserted. Closing and opening the widget settings it's still there but after updating the site the link disappears. Here in German there is no special character in the upload button, changing the language to English doesn't solve the problem either. Tried disabling all other plug-ins with no effect.
It is further more strange as the same wordpress/plug-in setup ist running on different pages and on one it's working right and on the other with this problem.

**Comment by rodica-andronache** [comment] 2018-01-08 14:00
Hi ,

Thank you for reporting this. Indeed there seems it was a problem in the Themeisle Companion plugin when using a different language than English. We'll release an update in the next days https://github.com/Codeinwp/themeisle-companion/pull/176 and we'll also investigate this for Zerif PRO.

Regards,
Rodica

**Comment by gschutz84** [comment] 2018-01-16 10:32
okay, thank you very much.
i changed 
`if ( ! empty( $instance['image_uri'] ) && ( $instance['image_uri'] != 'Upload Image' ) ) {`
with
`if ( ! empty( $instance['image_uri'] ) && ( preg_match('/(\.jpg|\.png|\.jpeg|\.gif|\.bmp)$/', $instance['image_uri'] ) ) ) {`
in inc/class/class-zerif-team-widget.php line 81 to fix the problem in zerif pro

regards,
Gerrit

**Comment by rodica-andronache** [comment] 2018-01-16 16:01
@gschutz84 great, we'll be adding that in Zerif PRO too in the next release :D 
Regards,
Rodica

**Closed as completed** 2018-05-02 10:45 UTC
