### ISSUE TITLE
Menu not closing on iOS Devices

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/zerif-lite#582] opened 2017-05-19 04:42 UTC
@rodica-andronache I tried Iphone 6S and iphone 7+ and it seems when you expand the menu it does not collapse if you try clicking the burger bar again.

I tried on safar, chrome and firefox with the same result. I tried on the samsung S6 and it didn't seem to have an issue

**Comment by rodica-andronache** [comment] 2018-03-16 15:06
@cosmin-serbanescu on my iphone 5 the menu is closing at first. The problem is when I open the menu, scroll a little and then try to close it. Indeed the menu stays extended, even though the text disappears.
I tested just the demo, https://demo.themeisle.com/zerif-lite/, where we are using this plugin https://wordpress.org/plugins/megamenu/ so, you need to take this into consideration, and test with or without it :)

**Comment by rodica-andronache** [comment] 2018-03-20 12:54
@cosmin-serbanescu at a closer look here http://wraith.themeisle.com/wraith/codeinwp/zerif-lite/development/gallery.html it seems that those lines you removed were used for the menu on tablet.
This is before https://prnt.sc/itrs21 on the demo https://demo.themeisle.com/zerif-lite/blog/
and this now https://prnt.sc/itrs79 http://forks.themeisle.com/codeinwp/zerif-lite/development/blog/
Could you please have another look? 💃 
We can talk about how wraith/forks work on slack if you want

**Closed as completed** 2018-03-21 12:31 UTC
Labels: bug
